#define CUB_VERSION_MAJOR 0
#define CUB_VERSION_MINOR 1
#define CUB_VERSION_PATCH 0

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define CUB_VERSION_STRING TOSTRING(CUB_VERSION_MAJOR) "." TOSTRING(CUB_VERSION_MINOR) "." TOSTRING(CUB_VERSION_PATCH)
